### ISSUE TITLE
Makieta

### ISSUE THREAD

**Issue by KevinCwiek** [TheGamesAmongUs/Dokumenty#5]
Popraw makietę. "Najpopularniejsze" i "najnowsze" daj do góry.
"Sidebar" daj w dół.
Logowanie i rejestracja ma zostać przeniesiona w prawy górny róg.
Mają być one w formie hyperlinków.
Po prawej stronie od miejsca na tekst do wyszukiwania zrob mały przycisk z lupą.

**Comment by RichForever** [comment]
Poprawiona wersja makiety została udostępniona na dysku google.
